AWSTemplateFormatVersion: '2010-09-09'
Description: Simple State Machine with an Activity

Parameters:
  StateMachineName:
    Type: String
    Description: The name of the State Machine

Resources:
  MyActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: !Sub "${StateMachineName}-Activity"

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StateMachineExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "logs:*"
                  - "sns:*"
                  - "sqs:*"
                  - "lambda:*"
                  - "dynamodb:*"
                  - "states:*"
                Resource: "*"

  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref StateMachineName
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        StartAt: MyActivity
        States:
          MyActivity:
            Type: Task
            Resource: !GetAtt MyActivity.Arn
            End: true

Outputs:
  StateMachineArn:
    Description: The ARN of the State Machine
    Value: !GetAtt MyStateMachine.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StateMachineArn"

  ActivityArn:
    Description: The ARN of the Activity
    Value: !GetAtt MyActivity.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ActivityArn"    